version: "2"

run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  
  settings:
    govet:
      enable:
        - appends
        - asmdecl
        - assign
        - atomic
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - directive
        - errorsas
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - shift
        - sigchanyzer
        - slog
        - stdmethods
        - stringintconv
        - structtag
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
      disable:
        - fieldalignment
        - shadow
    
    staticcheck:
      checks: ["all"]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0